### ISSUE TITLE
Unable to Sync kb_knowledge Table

### ISSUE THREAD

**Issue by AaronRichardsWFS** [gflewis/sndml3#15] opened 2020-04-22 13:34 UTC
So i have been using this to since key tables to report on for over 3 years and it has helped us so much by allowing us to create the advanced reports we need to manage our system.  Today i tried to add in the kb_knowledge table as we just started using the Knowledge module in February. When i add the table to the config.  It sees it creates the table in my SQL server see how many records are in the table but then just stops

Here is one of the other tables that doesn't have an issue:
09:28:16 INFO [main] LoaderJob sc_task INIT: getKeys sys_created_on<2020-04-22 13:20:02^sys_updated_on>=2020-04-20 13:20:02^ORDERBYsys_created_on^ORDERBYsys_id
09:28:16 INFO [main] LoaderJob sc_task INIT: begin load sc_task (13 rows)
09:28:17 INFO [main] DatabaseUpdateWriter sc_task PROCESS: loaded 13 / 13
09:28:17 INFO [main] LoaderJob sc_task FINISH: end load sc_task (13 rows)

Then here is what happens to the kb_knowledge table
09:28:17 INFO [main] RestTableAPI kb_knowledge PROCESS: getStats count=712 query="sys_created_on<2020-04-22 13:20:02^ORDERBYsys_created_on^ORDERBYsys_id"
09:28:17 INFO [main] LoaderJob kb_knowledge INIT: begin load kb_knowledge (712 rows)

and it just stops there.

I Saw you release 3.1.0 and i upgraded and tried that and same results.

**Comment by gflewis** [comment] 2020-05-17 02:48
I have not been able to reproduce this issue in my testing. There are some bug fixes in 3.1.1, so you might try that version to see if you get different results.

I suspect that you are having a timeout issue because your KB articles are too large, or there are some characters in the articles that are blocking the download. There is a new feature in 3.1.1 that allows loading of only selected columns. For example:

`{table: kb_knowledge, columns: number short_description kb_knowledge_base kb_category}`

You could try **not** loading the `text` field, and see if this makes a difference. If all other fields load without issue, then it would indicate an issue with the `text` field.

**Comment by gflewis** [comment] 2020-06-06 00:49
Can you let me know if you are still having trouble loading kb_knowledge? I would like to close this issue. I have had no problems loading kb_knowledge using 3.1.2.

**Comment by AaronRichardsWFS** [comment] 2020-06-08 15:29
I upgrade to latest SN Orlando Patch and the latest version of sndml3 and all is working now.  Thanks very much!

**Closed** 2020-06-11 23:09 UTC
